### PR TITLE
trivial: Add missing const identifier

### PR DESCRIPTION
**Pull request by nomadeel**
Signed-off-by: Damon Lee <Damon.Lee@data61.csiro.au>

### CODE REVIEW

**Comment by axel-h** [comment]
Goot catch and shame on me, I did not test this because we don't have a platform active for this yet. Maybe the github CI check should have a plat form that checks this configuration?

**Comment by nomadeel** [comment]
Do you mean the ssrg-bamboo test command?

**Comment by axel-h** [comment]
No, the builds that github runs. I did run bamboo on https://github.com/seL4/seL4_tools/pull/83 but this failed with something else.

**Review by ikuz — APPROVED** [review]

**Review by axel-h — APPROVED** [review]

**Comment by nomadeel** [comment]
The builds that github runs don't have any compilation tests though.

**Comment by lsf37** [comment]
> Good catch and shame on me, I did not test this because we don't have a platform active for this yet. Maybe the github CI check should have a platform that checks this configuration?

It probably should. I'm planning to spend some more actual time on GitHub CI again at some point in the next 2-3 weeks.

**Pull request merged**
