### PR TITLE
Fix RISC-V compilation with recent GCC

### PR DESCRIPTION
**Pull request by wom-bat**
Default args for gcc have changed; we need to fix the args given to the compiler.

### CODE REVIEW

**Comment by axel-h** [comment]
Seems this is https://github.com/seL4/seL4/issues/749 again.

**Comment by wom-bat** [comment]
> Seems this is [seL4/seL4#749](https://github.com/seL4/seL4/issues/749) again.

Yes, but the fix there didn't fix all the  flags.

**Comment by axel-h** [comment]
> Yes, but the fix there didn't fix all the flags.

You are referring to the CMake flags that are specific to OpenSBI, not some missing gcc flags, right? Because the change seem to be an exact copy of the flags.

**Review by axel-h — APPROVED** [review]
Looks good to me

**Comment by wom-bat** [comment]
Yep.

**Pull request merged**
