### PR TITLE
simulation: added rocketchip platform for qemu simulation

### PR DESCRIPTION
**Pull request by ruizjuanpablo**
Added rocketchip platform for qemu simulation script with the default
256MB of memory.

Signed-off-by: Juan Pablo Ruiz <juanpablo@ssrc.tii.ae>

### CODE REVIEW

**Review by axel-h — APPROVED** [review]

**Review by axel-h — COMMENTED** [review]
looks ok. Please address the remarks of the automatic checks.

**Comment by yyshen** [comment]
> Added rocketchip platform for qemu simulation script with the default
> 256MB of memory.
> 
> Signed-off-by: Juan Pablo Ruiz [juanpablo@ssrc.tii.ae](mailto:juanpablo@ssrc.tii.ae)

Is this related to the PR https://github.com/seL4/sel4test/pull/38? The 1GiB page test is disabled because QEMU uses 256MiB memory by default? Is that a hard limit? Can we use 2GiB memory instead?

**Comment by axel-h** [comment]
See also my other comments about this platform, I really wonder what the state here is or if this is an experimental platform that can be anything. Then we need more verbose comments everywhere which values are default configuration and which are customization.

**Comment by ruizjuanpablo** [comment]
I have fixed the git commit message style problem. Also, I added more verbose information indicating that the 256MB of memory is the default configuration in rocketchip.dts file.

**Comment by axel-h** [comment]
please remove the merge commit and rebase instead.

**Comment by ruizjuanpablo** [comment]
Sorry for the merge, my bad. I have removed the merge and rebased.

**Review by kent-mcleod — APPROVED** [review]

**Pull request merged**
