### PR TITLE
elfloader: refactor code to improve maintainability

### PR DESCRIPTION
**Pull request by axel-h**
Thanks for merging https://github.com/seL4/seL4_tools/pull/83, and here is another round of code cleanup. It also improved the output a bit to show what the ELF loading does. This turned out to be useful for debugging to see where things end up in memory during platform porting. For day-to-day usage with a focus on running booting system images this might be a bit too verbose, but I'd leave changing this to feedback on this PR. Adding a log level concept might be a follow-up task then.

### CODE REVIEW

**Comment by axel-h** [comment]
Can we merge this?

**Comment by kent-mcleod** [comment]
@axel-h, is it possible to reorganize these changes to make them easier to review? The way that the changes are currently presented in the diff viewer look as if there are > 700 lines of changes.  I'm assuming that this change isn't changing any functionality other than the added logging that you mentioned, but this is hard to review without going through every line.

**Comment by axel-h** [comment]
I can try to break this down in several commit with smaller incremental changes. May take a few day. But basically, this is a big rewrite of the code.

**Comment by kent-mcleod** [comment]
Making this a draft because I'm assuming @axel-h is still planning to break it up into several commits

**Comment by kent-mcleod** [comment]
@axel-h, can this be closed? It can be reopened or recreated in the future, but at this stage it's unlikely to be considered as a single commit rewrite.

**Comment by axel-h** [comment]
I've tried to split this up, but this takes more time in the end to make meaningful commits then. 
I'm closing this now.

**Pull request closed without merging**
