### PR TITLE
Change ELF library to BSD 3 Clause

### PR DESCRIPTION
**Pull request by xurtis**

### CODE REVIEW

**Review by lsf37 — APPROVED** [review]
👍

**Comment by lsf37** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Review by gernotheiser — APPROVED** [review]

**Comment by xurtis** [comment]
@gernotheiser please don't merge PRs on GitHub, it breaks all of our CI

**Pull request merged**
