### PR TITLE
add_fpu_compilation_options: More accurate checks

### PR DESCRIPTION
**Pull request by kent-mcleod**
The FPU checks need to check that the compiler can compile programs with
the desired FPU options AND link against compiler runtime libraries with
the correct FPU ABI. If either of these conditions aren't met, then we
can't build programs correctly.

We use the standard check_c_source_runs CMake function which inherits
the compilation options that have been set already. Unfortunately it
doesn't inherit any changes to CMAKE_<LANG>_LINK_EXECUTABLE variables
which is what we use to set the compiler libraries and so we need to
specify those again manually. This both compiles and links our test
program.  In cross-compiling environments, the run stage will be
skipped; yet this is still sufficient to pick up ABI mismatches.

### CODE REVIEW

**Comment by nomadeel** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by kent-mcleod** [comment]
@maybe-sybr, the changes in https://github.com/seL4/seL4_tools/pull/35 cause the test programs to no longer get linked against libgcc or the crt files which test compatible floating point abis.  This PR should still work on systems without an installed cross- C library but I can only test it on our docker container configurations.

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by maybe-sybr** [comment]
lgtm, seems much more sensible to make cmake do the heavy lifting for us!

It looks like the adder camkes app continues to build and function fine for me targeting zynq7k in a clean tree with the Fedora xcompilers:

```
$ ../init-build.sh -DPLATFORM=zynq7000 -DCROSS_COMPILER_PREFIX=arm-linux-gnu-
...
-- Performing Test HARD_FLOAT
-- Performing Test HARD_FLOAT - Success
-- Performing Test compiler_arch_test
-- Performing Test compiler_arch_test - Success
-- Detecting cached version of: musllibc
--   Not found cache entry for musllibc - will build from source
...
$ ninja
...
$ ./simulate
...
Enabling MMU and paging
Bootstrapping kernel
Warning: Could not infer GIC interrupt target ID, assuming 0.
Booting all finished, dropped to user space
client: what's the answer to 342 + 74 + 283 + 37 + 534 ?
adder: Adding 342
adder: Adding 74
adder: Adding 283
adder: Adding 37
adder: Adding 534
client: result was 1270
QEMU: Terminated
```

**Pull request merged**
