### PR TITLE
The aarch32 json target

### PR DESCRIPTION
**Pull request by ridale**
Tested against sabre in simulator.

### CODE REVIEW

**Comment by kent-mcleod** [comment]
Thanks, which apps are you using to test these?

@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit b8b1a2f2e65a654a98a7a4beff6097e9232b4f1a

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - seL4_tools - EXT-ridale-ridale-aarch32-34 | SUCCESSFUL |
| Code Quality - Style - seL4_tools - EXT-ridale-ridale-aarch32-34 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - seL4_tools - EXT-ridale-ridale-aarch32-34 | Style check on changed files | 1 of 3 jobs failed |

**Job: gitlint**
Build logs

    22-Nov-2019 09:34:30	Build Code Quality - Style - seL4_tools - EXT-ridale-ridale-aarch32-34 - gitlint #1 (CQ-SEL4TOOLSSTYLE118-SEL4TOOLSGITLINTPR-1) started building on agent A local agent 1
    22-Nov-2019 09:34:30	I run on the Bamboo server!
    22-Nov-2019 09:34:30	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TOOLSSTYLE118-SEL4TOOLSGITLINTPR
    22-Nov-2019 09:34:30	Executing build Code Quality - Style - seL4_tools - EXT-ridale-ridale-aarch32-34 - gitlint #1 (CQ-SEL4TOOLSSTYLE118-SEL4TOOLSGITLINTPR-1)
    22-Nov-2019 09:34:30	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TOOLSSTYLE118-SEL4TOOLSGITLINTPR/. (location: .)
    22-Nov-2019 09:34:30	Artifact 'code' prepared in 24.92 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TOOLSSTYLE118-SEL4TOOLSGITLINTPR/./code.tar.gz
    22-Nov-2019 09:34:30	Running pre-build action: VCS Version Collector
    22-Nov-2019 09:34:30	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    22-Nov-2019 09:34:30	+ tar xf code.tar.gz --recursive-unlink
    22-Nov-2019 09:34:30	Finished task 'Untar code' with result: Success
    22-Nov-2019 09:34:30	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    22-Nov-2019 09:34:30	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TOOLSSTYLE118-SEL4TOOLSGITLINTPR
    22-Nov-2019 09:34:30	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    22-Nov-2019 09:34:30	Starting task 'Lint commit messages' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    22-Nov-2019 09:34:30	+ cd seL4_tools
    22-Nov-2019 09:34:30	+ gitlint --commits master..b8b1a2f2e65a654a98a7a4beff6097e9232b4f1a --config /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TOOLSSTYLE118-SEL4TOOLSGITLINTPR/seL4_tools/misc/.gitlint
    22-Nov-2019 09:34:33	3: B6 Body message is missing
    22-Nov-2019 09:34:33	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4TOOLSSTYLE118-SEL4TOOLSGITLINTPR-1-ScriptBuildTask-1451871681537708509.sh] was 1 while expected 0
    22-Nov-2019 09:34:33	Finished task 'Lint commit messages' with result: Failed
    22-Nov-2019 09:34:33	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    22-Nov-2019 09:34:33	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TOOLSSTYLE118-SEL4TOOLSGITLINTPR
    22-Nov-2019 09:34:33	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    22-Nov-2019 09:34:33	Running post build plugin 'NCover Results Collector'
    22-Nov-2019 09:34:33	Running post build plugin 'Artifact Copier'
    22-Nov-2019 09:34:33	Running post build plugin 'npm Cache Cleanup'
    22-Nov-2019 09:34:33	Running post build plugin 'Clover Results Collector'
    22-Nov-2019 09:34:33	Running post build plugin 'Docker Container Cleanup'
    22-Nov-2019 09:34:33	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4TOOLSSTYLE118-SEL4TOOLSGITLINTPR'
    22-Nov-2019 09:34:33	Finalising the build...
    22-Nov-2019 09:34:33	Stopping timer.
    22-Nov-2019 09:34:33	Build CQ-SEL4TOOLSSTYLE118-SEL4TOOLSGITLINTPR-1 completed.
    22-Nov-2019 09:34:33	Running on server: post build plugin 'NCover Results Collector'
    22-Nov-2019 09:34:33	Running on server: post build plugin 'Build Hanging Detection Configuration'
    22-Nov-2019 09:34:33	Running on server: post build plugin 'Clover Delta Calculator'
    22-Nov-2019 09:34:33	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    22-Nov-2019 09:34:33	All post build plugins have finished
    22-Nov-2019 09:34:33	Generating build results summary...
    22-Nov-2019 09:34:33	Saving build results to disk...
    22-Nov-2019 09:34:33	Logging substituted variables...
    22-Nov-2019 09:34:33	Indexing build results...
    22-Nov-2019 09:34:33	Finished building CQ-SEL4TOOLSSTYLE118-SEL4TOOLSGITLINTPR-1.


This is the most I can report on right now, sorry!

**Comment by ridale** [comment]
Using the hellorust app to test.

../init-build.sh -DPLATFORM=sabre -DCAMKES_APP=hellorust
../init-build.sh -DPLATFORM=x86_64 -DCAMKES_APP=hellorust

followed by ./simulate

**Pull request merged**
