### PR TITLE
Add a commands for QEMU and GDB debugging in simulate script

### PR DESCRIPTION
**Pull request by mokshasoft**

### CODE REVIEW

**Comment by nomadeel** [comment]
Hey, sorry for the late response. This PR looks mostly fine but there are some minor issues to take care of. I'll resolve these and then try to pull this patch in. Let me know if you have any concerns with this and I'll be happy to help.

**Comment by nomadeel** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit bd41aa1c17aa79ad532fe12c642f1ce05c71c327

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - seL4_tools - EXT-mokshasoft-sim-gdb-23 | SUCCESSFUL |
| Code Quality - Style - seL4_tools - EXT-mokshasoft-sim-gdb-23 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - seL4_tools - EXT-mokshasoft-sim-gdb-23 | Style check on changed files | 1 of 3 jobs failed |

**Job: gitlint**
Build logs

    20-Nov-2019 11:16:17	Build Code Quality - Style - seL4_tools - EXT-mokshasoft-sim-gdb-23 - gitlint #1 (CQ-SEL4TOOLSSTYLE115-SEL4TOOLSGITLINTPR-1) started building on agent A local agent 2
    20-Nov-2019 11:16:17	I run on the Bamboo server!
    20-Nov-2019 11:16:17	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TOOLSSTYLE115-SEL4TOOLSGITLINTPR
    20-Nov-2019 11:16:17	Executing build Code Quality - Style - seL4_tools - EXT-mokshasoft-sim-gdb-23 - gitlint #1 (CQ-SEL4TOOLSSTYLE115-SEL4TOOLSGITLINTPR-1)
    20-Nov-2019 11:16:17	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TOOLSSTYLE115-SEL4TOOLSGITLINTPR/. (location: .)
    20-Nov-2019 11:16:17	Artifact 'code' prepared in 29.04 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TOOLSSTYLE115-SEL4TOOLSGITLINTPR/./code.tar.gz
    20-Nov-2019 11:16:17	Running pre-build action: VCS Version Collector
    20-Nov-2019 11:16:17	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    20-Nov-2019 11:16:17	+ tar xf code.tar.gz --recursive-unlink
    20-Nov-2019 11:16:17	Finished task 'Untar code' with result: Success
    20-Nov-2019 11:16:17	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    20-Nov-2019 11:16:17	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TOOLSSTYLE115-SEL4TOOLSGITLINTPR
    20-Nov-2019 11:16:17	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    20-Nov-2019 11:16:17	Starting task 'Lint commit messages' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    20-Nov-2019 11:16:17	+ cd seL4_tools
    20-Nov-2019 11:16:17	+ gitlint --commits master..bd41aa1c17aa79ad532fe12c642f1ce05c71c327 --config /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TOOLSSTYLE115-SEL4TOOLSGITLINTPR/seL4_tools/misc/.gitlint
    20-Nov-2019 11:16:21	3: B6 Body message is missing
    20-Nov-2019 11:16:21	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4TOOLSSTYLE115-SEL4TOOLSGITLINTPR-1-ScriptBuildTask-7714708289983029299.sh] was 1 while expected 0
    20-Nov-2019 11:16:21	Finished task 'Lint commit messages' with result: Failed
    20-Nov-2019 11:16:21	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    20-Nov-2019 11:16:21	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TOOLSSTYLE115-SEL4TOOLSGITLINTPR
    20-Nov-2019 11:16:21	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    20-Nov-2019 11:16:21	Running post build plugin 'NCover Results Collector'
    20-Nov-2019 11:16:21	Running post build plugin 'Artifact Copier'
    20-Nov-2019 11:16:21	Running post build plugin 'npm Cache Cleanup'
    20-Nov-2019 11:16:21	Running post build plugin 'Clover Results Collector'
    20-Nov-2019 11:16:21	Running post build plugin 'Docker Container Cleanup'
    20-Nov-2019 11:16:21	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4TOOLSSTYLE115-SEL4TOOLSGITLINTPR'
    20-Nov-2019 11:16:21	Finalising the build...
    20-Nov-2019 11:16:21	Stopping timer.
    20-Nov-2019 11:16:21	Build CQ-SEL4TOOLSSTYLE115-SEL4TOOLSGITLINTPR-1 completed.
    20-Nov-2019 11:16:21	Running on server: post build plugin 'NCover Results Collector'
    20-Nov-2019 11:16:21	Running on server: post build plugin 'Build Hanging Detection Configuration'
    20-Nov-2019 11:16:21	Running on server: post build plugin 'Clover Delta Calculator'
    20-Nov-2019 11:16:21	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    20-Nov-2019 11:16:21	All post build plugins have finished
    20-Nov-2019 11:16:21	Generating build results summary...
    20-Nov-2019 11:16:21	Saving build results to disk...
    20-Nov-2019 11:16:21	Logging substituted variables...
    20-Nov-2019 11:16:21	Indexing build results...
    20-Nov-2019 11:16:21	Finished building CQ-SEL4TOOLSSTYLE115-SEL4TOOLSGITLINTPR-1.


This is the most I can report on right now, sorry!

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by mokshasoft** [comment]
Thanks, for me it's fine if you fix and pull it.

**Pull request merged**
