### PR TITLE
Add basic style CI checks

### PR DESCRIPTION
**Pull request by lsf37**
This is the basic set from https://github.com/seL4/ci-actions

### CODE REVIEW

**Comment by lsf37** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
