### PR TITLE
Bring Raspberry Pi 4 (RPi4) support

### PR DESCRIPTION
**Pull request by lulu98**
Signed-off-by: Lukas Graber <lukas.graber@hensoldt-cyber.de>

### CODE REVIEW

**Comment by lulu98** [comment]
- PR in util_libs: https://github.com/seL4/util_libs/pull/60
- PR in seL4: https://github.com/seL4/seL4/pull/293

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Review by oliver-wm — APPROVED** [review]

**Comment by oliver-wm** [comment]
I will merge all of these rpi4 prs and deal with the fallout once we have rpi4 connected to our machine queue.

**Pull request closed without merging**
